### ISSUE TITLE
request to change path to gun

### ISSUE THREAD

**Issue by Stefdv** [d3x0r/gun-file#1]
'gun-file' 
```const Gun = require('gun/gun') ``` This will load gun from the gun-file folder. This results in Gun getting loaded twice ( if you have Gun already assigned ) 

I propose that you change it to ```const Gun = require('../gun/gun') ``` so it will use the main Gun

**Comment by d3x0r** [comment]
it should be using the main gun... if it's not it's a problem in the package.json

  "dependencies": { "json-6":"^0", "gun":"^0.8.0" }
 should be 0.9.0 now?
should be pushed and published as 1.0.119

**Comment by Stefdv** [comment]
Yes, package.json is correct...stil it installs gun in 'gun-file' -> 'node-modules' ?

**Comment by d3x0r** [comment]
well... what's your package.json dependancy for gun?  I ran into that before... I think it's more of an issue with NPM... 

modified it to `const Gun = require(module.filename.includes( "node_modules/gun-file" )?'../gun/gun':'gun/gun');`

**Comment by Stefdv** [comment]
Don't know what happened... started out in a fresh folder and it installs correct. 
Case closed 👍
